# Generated by Django 4.0.6 on 2022-07-08 13:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(auto_now=True)),
                ('isbn', models.CharField(max_length=13)),
                ('expiry_date', models.DateField(default=app.models.expiry)),
            ],
        ),
    ]
