# Generated by Django 4.0.6 on 2022-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_issuedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
